# Send a message when a player attempts to create a blocked item
alert: true
recipe:
  mode: blacklist
  # Material names can be found here:
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html#enum-constant-summary
  # Any material name containing the listed string will be counted. ex: "pickaxe" will block all pickaxes
  list:
    - "wood"
    - "pickaxe"
potions:
  # Options: whitelist, blacklist, disable
  mode: blacklist
  list:
    - "HEAL"
    - "REGEN"
# Should the plugin to tell you on login when there is an update available
check_for_updates: true
# Should the plugin to send bStats info.
enable_metrics: true