name: NoCraftPlus
main: com.devmclovin.nocraftplus.NoCraftPlugin
version: 3.0.0
api-version: 1.21
commands:
  nocraftplus:
    description: Base command.
    aliases: [ncp]
permissions:
  nocraftplus.*:
    children:
      nocraftplus.bypass.*: true
      nocraftplus.command: true
      nocraftplus.updatecheck: true
  nocraftplus.bypass.*:
    description: Bypass all item filters.
  nocraftplus.bypass.<item>:
    description: Bypass specific item filter.
  nocraftplus.command:
    description: Access to command.
  nocraftplus.updatecheck:
    description: Alert when update is available.